---
abstract: 'solve a CAPTCHA before some actions in RT'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-Captcha
no_index:
  directory:
    - etc
    - html
    - inc
requires:
  GD::SecurityImage: 0
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/bestpractical/rt-extension-captcha
version: '1.21'
x_module_install_rtx_version: '0.42'
x_requires_rt: 4.2.0
